const REPORTS_KEY = "securescan_reports";
const REPORTS_CLEARED_AT_KEY = "securescan_reports_cleared_at";

function readReports() {
  try {
    const saved = JSON.parse(localStorage.getItem(REPORTS_KEY) || "[]");
    return Array.isArray(saved) ? saved : [];
  } catch {
    return [];
  }
}

function writeReports(reports) {
  localStorage.setItem(REPORTS_KEY, JSON.stringify(reports.slice(0, 200)));
  window.dispatchEvent(new Event("securescan-reports-updated"));
}

export function getReportsClearedAt() {
  const value = Number(localStorage.getItem(REPORTS_CLEARED_AT_KEY) || 0);
  return Number.isFinite(value) ? value : 0;
}

export function markReportsCleared() {
  const clearedAt = Date.now();
  localStorage.setItem(REPORTS_CLEARED_AT_KEY, String(clearedAt));
  writeReports([]);
  return clearedAt;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function buildReportHtml({ fileName, fileSize, result, analysisId, generatedAt }) {
  const malicious = Number(result?.malicious || 0);
  const suspicious = Number(result?.suspicious || 0);
  const harmless = Number(result?.harmless || 0);
  const undetected = Number(result?.undetected || 0);
  const total = malicious + suspicious + harmless + undetected;
  const status = malicious > 0
    ? "Malicious Threat Detected"
    : suspicious > 0
      ? "Suspicious Activity Detected"
      : "No Major Threats Detected";
  const statusClass = malicious > 0 ? "danger" : suspicious > 0 ? "warning" : "safe";

  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SecureScan Report - ${escapeHtml(fileName)}</title><style>body{font-family:Arial,Helvetica,sans-serif;background:#f5f8fc;color:#17213a;margin:0;padding:36px}.report{max-width:850px;margin:auto;background:#fff;border:1px solid #dfe7f2;border-radius:18px;padding:32px;box-shadow:0 15px 40px rgba(15,35,65,.08)}h1{margin:0;color:#2563eb}.muted{color:#738097}.status{margin:24px 0;padding:16px;border-radius:10px;font-weight:700}.danger{background:#fff1f3;color:#c52e40}.warning{background:#fff7e8;color:#b56b08}.safe{background:#effaf3;color:#168447}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:12px;border-bottom:1px solid #e8edf4;text-align:left}th{width:35%;background:#f8fafc}.footer{margin-top:24px;font-size:12px;color:#98a3b3}</style></head><body><main class="report"><h1>SecureScan Security Report</h1><p class="muted">Generated ${escapeHtml(generatedAt)}</p><div class="status ${statusClass}">${escapeHtml(status)}</div><table><tr><th>File</th><td>${escapeHtml(fileName)}</td></tr><tr><th>Size</th><td>${Number(fileSize || 0) / 1024 / 1024 < 1 ? (Number(fileSize || 0) / 1024).toFixed(1) + " KB" : (Number(fileSize || 0) / 1024 / 1024).toFixed(2) + " MB"}</td></tr><tr><th>VirusTotal Analysis ID</th><td>${escapeHtml(analysisId || "N/A")}</td></tr><tr><th>Malicious</th><td>${malicious}</td></tr><tr><th>Suspicious</th><td>${suspicious}</td></tr><tr><th>Harmless</th><td>${harmless}</td></tr><tr><th>Undetected</th><td>${undetected}</td></tr><tr><th>Total Engines</th><td>${total}</td></tr></table><p class="footer">This report was generated by SecureScan from the stored scan result.</p></main></body></html>`;
}

export function saveReport(report) {
  const reports = readReports();
  const existingIndex = reports.findIndex((item) => item.id === report.id);
  if (existingIndex >= 0) reports[existingIndex] = { ...reports[existingIndex], ...report };
  else reports.unshift(report);
  writeReports(reports);
  return report;
}

export function getReports() {
  return readReports();
}

export function deleteReport(id) {
  writeReports(readReports().filter((item) => item.id !== id));
}

export function clearReports() {
  return markReportsCleared();
}

export function downloadStoredReport(report) {
  const blob = new Blob([report.html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = report.fileNameOnDisk || `SecureScan-Report-${String(report.fileName || "scan").replace(/[^a-z0-9._-]/gi, "_")}.html`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export { REPORTS_KEY };
